name: Deploy to Server

on:
  push:
    branches: [ main ]  # 监听main分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CI: false  # 全局环境变量

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: build
      env:
          bucket: ${{ secrets.bucket }}
          region: ${{ secrets.region }}
          accessKeyId: ${{ secrets.accessKeyId }}
          accessKeySecret: ${{ secrets.accessKeySecret }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_VISION_MODEL: ${{ secrets.OPENAI_VISION_MODEL }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_API_KEY_GITEE: ${{ secrets.DEEPSEEK_API_KEY_GITEE }}

      run: |
        npm install
        npm run build

    - name: scp pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SERVER_IP }}
        user: ${{ secrets.USER }}
        pass: ${{ secrets.PASSWORD }}
        first_ssh: |
          rm -rf /root/be_right/.next
        scp: |
          './.next' => /root/be_right
